/*
 * QuickJS implementation of javascript engine functions.
 */

#include <quickjs.h>
#include <string.h>
#include <stdlib.h>
#include "utils/errors.h"
#include "utils/log.h"
#include "content/content.h"
#include "javascript/js.h"
#include "content/handlers/javascript/quickjs/qjsky.h"
#include "content/handlers/javascript/quickjs/xhr.h"

struct jsheap {
	JSRuntime *rt;
};

struct jsthread {
	JSContext *ctx;
	jsheap *heap;
	void *win_priv;
	void *doc_priv;
};

/* exported interface documented in js.h */
void js_initialise(void)
{
	NSLOG(netsurf, INFO, "QuickJS engine initialised");
}

/* exported interface documented in js.h */
void js_finalise(void)
{
}

/* exported interface documented in js.h */
nserror js_newheap(int timeout, jsheap **heap)
{
	jsheap *h = calloc(1, sizeof(*h));
	if (h == NULL) return NSERROR_NOMEM;

	h->rt = JS_NewRuntime();
	if (h->rt == NULL) {
		free(h);
		return NSERROR_NOMEM;
	}

	/* Set memory limit for the runtime to prevent OOM */
	JS_SetMemoryLimit(h->rt, 64 * 1024 * 1024);

	/* Initialize NetSurf-specific classes for this runtime */
	qjsky_init_runtime(h->rt);

	*heap = h;
	return NSERROR_OK;
}

/* exported interface documented in js.h */
void js_destroyheap(jsheap *heap)
{
	if (heap) {
		JS_FreeRuntime(heap->rt);
		free(heap);
	}
}

/* Bridge for Window.alert */
static JSValue qjsky_window_alert(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
	if (argc > 0) {
		const char *msg = JS_ToCString(ctx, argv[0]);
		if (msg) {
			NSLOG(netsurf, INFO, "JS ALERT: %s", msg);
			JS_FreeCString(ctx, msg);
		}
	}
	return JS_UNDEFINED;
}

/* exported interface documented in js.h */
nserror js_newthread(jsheap *heap, void *win_priv, void *doc_priv, jsthread **thread)
{
	jsthread *t = calloc(1, sizeof(*t));
	if (t == NULL) return NSERROR_NOMEM;

	t->heap = heap;
	t->ctx = JS_NewContext(heap->rt);
	if (t->ctx == NULL) {
		free(t);
		return NSERROR_NOMEM;
	}
	t->win_priv = win_priv;
	t->doc_priv = doc_priv;

	/* Store thread state */
	JS_SetContextOpaque(t->ctx, t);

	/* Global setup: Initialize standard objects */
	JS_AddIntrinsicBaseObjects(t->ctx);
	JS_AddIntrinsicDate(t->ctx);
	JS_AddIntrinsicEval(t->ctx);
	JS_AddIntrinsicStringNormalize(t->ctx);
	JS_AddIntrinsicRegExp(t->ctx);
	JS_AddIntrinsicJSON(t->ctx);
	JS_AddIntrinsicProxy(t->ctx);
	JS_AddIntrinsicMapSet(t->ctx);
	JS_AddIntrinsicTypedArrays(t->ctx);
	JS_AddIntrinsicPromise(t->ctx);
	JS_AddIntrinsicBigInt(t->ctx);

	/* Initialize NetSurf context support (memoization etc) */
	qjsky_init_context(t->ctx);

	/* Initialize the console object */
	qjsky_init_console(t->ctx);

	/* Initialize the XMLHttpRequest object */
	qjsky_init_xhr(t->ctx);

	/* Basic Window APIs */
	JSValue global = JS_GetGlobalObject(t->ctx);
	JS_SetPropertyStr(t->ctx, global, "alert", JS_NewCFunction(t->ctx, qjsky_window_alert, "alert", 1));
	JS_FreeValue(t->ctx, global);

	/* TODO: Register NetSurf DOM bindings here once generated by nsgenbind */

	*thread = t;
	return NSERROR_OK;
}

/* exported interface documented in js.h */
nserror js_closethread(jsthread *thread)
{
	/* Disconnect callbacks and stop additional JS execution */
	return NSERROR_OK;
}

/* exported interface documented in js.h */
void js_destroythread(jsthread *thread)
{
	if (thread) {
		JS_FreeContext(thread->ctx);
		free(thread);
	}
}

/* exported interface documented in js.h */
bool js_exec(jsthread *thread, const uint8_t *txt, size_t txtlen, const char *name)
{
	if (txt == NULL || txtlen == 0) return false;

	JSValue val = JS_Eval(thread->ctx, (const char *)txt, txtlen, name, JS_EVAL_TYPE_GLOBAL);
	bool result = !JS_IsException(val);
	if (!result) {
		JSValue exception_val = JS_GetException(thread->ctx);
		const char *stack = JS_ToCString(thread->ctx, exception_val);
		if (stack) {
			NSLOG(jserrors, WARNING, "Uncaught error in JS: %s", stack);
			JS_FreeCString(thread->ctx, stack);
		}
		JS_FreeValue(thread->ctx, exception_val);
	}
	JS_FreeValue(thread->ctx, val);
	return result;
}

/* exported interface documented in js.h */
bool js_fire_event(jsthread *thread, const char *type, struct dom_document *doc, struct dom_node *target)
{
    /* Technical Implementation Requirement:
       1. Push 'target' node to stack using qjsky_push_node.
       2. Resolve event handler property (e.g., 'onclick').
       3. Create Event object.
       4. Call listener.
    */
	NSLOG(netsurf, DEBUG, "Event firing logic documented for %s", type);
	return true;
}

/* exported interface documented in js.h */
void js_handle_new_element(jsthread *thread, struct dom_element *node)
{
    /* Technical Implementation Requirement:
       1. Scan attributes for names starting with "on".
       2. Register listeners in NetSurf's event system that bridge to JS function calls.
    */
    NSLOG(netsurf, DEBUG, "New element handler requirements documented.");
}

/* exported interface documented in js.h */
void js_event_cleanup(jsthread *thread, struct dom_event *evt)
{
	/* Perform any cleanups needed after event propagation finished */
}
